### ISSUE TITLE
Daphne websocket ping errors

### ISSUE THREAD

**Issue by soulhunter1987** [django/daphne#123]
Hi.

Sometimes I get such error in log:
```
Jun 09 18:01:12 backend python[8299]: 2017-06-09 15:01:12,584 CRITICAL Unhandled Error
Jun 09 18:01:12 backend python[8299]: Traceback (most recent call last):
Jun 09 18:01:12 backend python[8299]:   File "/var/www/guidephone/backend/lib/python3.5/site-packages/daphne/cli.py", line 218, in run
Jun 09 18:01:12 backend python[8299]:     self.server.run()
Jun 09 18:01:12 backend python[8299]:   File "/var/www/guidephone/backend/lib/python3.5/site-packages/daphne/server.py", line 126, in run
Jun 09 18:01:12 backend python[8299]:     reactor.run(installSignalHandlers=self.signal_handlers)
Jun 09 18:01:12 backend python[8299]:   File "/var/www/guidephone/backend/lib/python3.5/site-packages/twisted/internet/base.py", line 1243, in run
Jun 09 18:01:12 backend python[8299]:     self.mainLoop()
Jun 09 18:01:12 backend python[8299]:   File "/var/www/guidephone/backend/lib/python3.5/site-packages/twisted/internet/base.py", line 1252, in mainLoop
Jun 09 18:01:12 backend python[8299]:     self.runUntilCurrent()
Jun 09 18:01:12 backend python[8299]: --- <exception caught here> ---
Jun 09 18:01:12 backend python[8299]:   File "/var/www/guidephone/backend/lib/python3.5/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
Jun 09 18:01:12 backend python[8299]:     call.func(*call.args, **call.kw)
Jun 09 18:01:12 backend python[8299]:   File "/var/www/guidephone/backend/lib/python3.5/site-packages/daphne/server.py", line 193, in timeout_checker
Jun 09 18:01:12 backend python[8299]:     self.factory.check_timeouts()
Jun 09 18:01:12 backend python[8299]:   File "/var/www/guidephone/backend/lib/python3.5/site-packages/daphne/http_protocol.py", line 434, in check_timeouts
Jun 09 18:01:12 backend python[8299]:     protocol.check_ping()
Jun 09 18:01:12 backend python[8299]:   File "/var/www/guidephone/backend/lib/python3.5/site-packages/daphne/ws_protocol.py", line 248, in check_ping
Jun 09 18:01:12 backend python[8299]:     if self.duration() > self.main_factory.websocket_connect_timeout:
Jun 09 18:01:12 backend python[8299]: builtins.TypeError: unorderable types: float() > NoneType()
```

And after that websocket pings stop working, in all socket connections untill server restart
As I see, this param websocket_connect_timeout is obtained from CLI argument and it's default value is set to None (asuming no timeout). So line 248 in ws_protocol.py shoulb be changed to "if self.main_factory.websocket_connect_timeout and self.duration() > self.main_factory.websocket_connect_timeout:"

**Comment by andrewgodwin** [comment]
I've set a default for 5 seconds instead.

**Comment by soulhunter1987** [comment]
Could you, please, roll out a release? There are two important fixes in master already (including this one)

**Comment by andrewgodwin** [comment]
Yes, I am going to do it now, I didn't realise how long it had been.

**Comment by andrewgodwin** [comment]
OK, 1.1.4 is now out.
