### ISSUE TITLE
Daphne doesn't drop connections when channel layer goes down

### ISSUE THREAD

**Issue by ollamh** [django/daphne#147]
## Bug description
Hi all,
As it is said in ASGI specification (https://channels.readthedocs.io/en/1.1.8/asgi.html):

**That said, if a channel server goes down momentarily and loses all data, persistent socket connections will continue to transfer incoming data and send out new generated data, but will have lost all of their group memberships and in-flight messages.
In order to avoid a nasty set of bugs caused by these half-deleted sockets, protocol servers should quit and hard restart if they detect that the channel layer has gone down or lost data; shedding all existing connections and letting clients reconnect will immediately resolve the problem.**

and I expect that Daphne server drops all connections when detects that channel layer is down until it goes up thus preventing new messages to be sent.

Instead of that I see that Daphne server keeps open all connections which are unusable. I don't receive anything via them even after channel layer is up and running (including `channels` workers)

Using `asgi_redis` packages as channel layer shows that the `channels` workers are got restarted after receiving `redis.exceptions.ConnectionError`:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/channels/management/commands/runworker.py", line 83, in handle
    worker.run()
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/channels/worker.py", line 87, in run
    channel, content = self.channel_layer.receive_many(channels, block=True)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/asgiref/base_layer.py", line 43, in receive_many
    return self.receive(channels, block)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/asgi_redis/core.py", line 204, in receive
    result = connection.blpop(list_names, timeout=self.blpop_timeout)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/redis/client.py", line 1269, in blpop
    return self.execute_command('BLPOP', *keys)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/redis/client.py", line 673, in execute_command
    connection.send_command(*args)
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/redis/connection.py", line 610, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/redis/connection.py", line 585, in send_packed_command
    self.connect()
  File "/var/backend/quokky_backend/virtual/local/lib/python2.7/site-packages/redis/connection.py", line 489, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to instance-name.cache.amazonaws.com:6379. Connection refused.
2017-12-20 13:13:35,973 - INFO - runworker - Using single-threaded worker.
2017-12-20 13:13:35,974 - INFO - runworker - Running worker against channel layer default (asgi_redis.core.RedisChannelLayer)
2017-12-20 13:13:35,975 - INFO - worker - Listening on channels websocket.connect, websocket.disconnect, websocket.receive
```

I believe the problem is in the line `daphne/server.py:141`, where it is using `try ... except Exception` which covers all possible exceptions which is also covers the case when it should drop all open connections instead of waiting 5 seconds.
```
        try:
            channel, message = self.channel_layer.receive(channels, block=False)
        except Exception as e:  <--
            # Log the error and wait a bit to retry
            logger.error('Error trying to receive messages: %s' % e)
            delay = 5.00
```

**Comment by andrewgodwin** [comment]
Agreed this does not match what the spec claims - however, the problem with that spec (which has since been retired) is that there was no signal to determine _when_ the channel layer had gone down as opposed to brief network interruption.

It's likely I won't fix this one before Daphne 2 is officially released as doing so would require a lot more work than just changing the try/except you highlighted, as well as a whole new round of testing. I'll leave it open though in case we can get to it, and close it when Daphne 2 is released and removes this problem via architectural redesign,

**Comment by ollamh** [comment]
@andrewgodwin Thanks for an update! 
I agree that there's a lot of work to change daphne behaviour, but is there any advice how we can overcome this issue? We're using daphne with supervisord and there are some workarounds which can restart all processes in the group if one is down (`channels` worker). Any ideas are welcome.

Is there any milestone for Daphne 2? Is there going to be any beta testing? I would definitely like to try it since we're already using daphne in production.

**Comment by andrewgodwin** [comment]
I'm afraid there's no roadmap for Channels/Daphne 2 in terms of hard dates; this is a volunteer project after all and I'm not paid for it any more. I'll see if there's an interim fix I can do for the current code to make it work more as claimed, but it'll have to wait until after I get back from holiday travel.

**Comment by andrewgodwin** [comment]
Daphne and Channels 2 are now released, closing as this is no longer needed!
