### ISSUE TITLE
Setting REDIS_PORT env raising error

### ISSUE THREAD

**Issue by nickmetal** [django/daphne#151]
ENV:

Ubuntu "16.04.3 LTS (Xenial Xerus)"
python3.6
pip freeze:

amqp==1.4.9
anyjson==0.3.3
appdirs==1.4.3
asgi-redis==1.4.3
asgiref==1.1.2
asn1crypto==0.22.0
astroid==1.5.3
attrs==17.2.0
autobahn==17.9.3
Automat==0.6.0
billiard==3.3.0.23
cffi==1.9.1
channels==1.1.8
click==6.7
constantly==15.1.0
cryptography==2.1.4
daphne==1.3.0
decorator==4.0.10
Django==1.11

I try to run:
```sh
$ REDIS_PORT=4444 /opt/venv/daphne -b 0.0.0.0 -p 8888 --ws-protocol "graphql-ws" --proxy-headers app.asgi:channel_layer
```
And i faced with error:

```python

Traceback (most recent call last):
  File "/opt/venv/bin/daphne", line 11, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/opt/venv/lib/python3.6/site-packages/daphne/cli.py", line 144, in entrypoint
    cls().run(sys.argv[1:])
  File "/opt/venv/lib/python3.6/site-packages/daphne/cli.py", line 174, in run
    channel_layer = importlib.import_module(module_path)
  File "/opt/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./nor_tk/asgi.py", line 10, in <module>
    channel_layer = channels.asgi.get_channel_layer()
  File "/opt/venv/lib/python3.6/site-packages/channels/asgi.py", line 118, in get_channel_layer
    return channel_layers[alias].channel_layer
  File "/opt/venv/lib/python3.6/site-packages/channels/asgi.py", line 70, in __getitem__
    self.backends[key] = self.make_backend(key)
  File "/opt/venv/lib/python3.6/site-packages/channels/asgi.py", line 33, in make_backend
    return self._make_backend(name, config)
  File "/opt/venv/lib/python3.6/site-packages/channels/asgi.py", line 61, in _make_backend
    asgi_layer = backend_class(**config)
  File "/opt/venv/lib/python3.6/site-packages/asgi_redis/core.py", line 538, in __init__
    self.hosts = self._setup_hosts(hosts)
  File "/opt/venv/lib/python3.6/site-packages/asgi_redis/core.py", line 567, in _setup_hosts
    final_hosts.append("redis://%s:%d/0" % (entry[0], entry[1]))
TypeError: %d format: a number is required, not str
```

In /opt/venv/lib/python3.6/site-packages/asgi_redis/core.py file on 538 line: 
print(hosts) ->  [('localhost', '4444')]

**Comment by andrewgodwin** [comment]
Don't use the `REDIS_PORT` environment variable, set it via the django settings instead please.
