### ISSUE TITLE
daphne==2.0.0 does not work on python 2.7

### ISSUE THREAD

**Issue by bastbnl** [django/daphne#155]
I updated to `daphne==2.0.0` and `channels==2.0.0` today to learn the project will not start anymore:

```
Unhandled exception in thread started by <function wrapper at 0x7ff96df7bde8>
Traceback (most recent call last):
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 236, in wrapper
    filename = traceback.extract_tb(tb)[-1][0]
TypeError: 'NoneType' object is not callable
Unhandled exception in thread started by <function wrapper at 0x7fa52124dd70>
Traceback (most recent call last):
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/django/apps/config.py", line 120, in create
    mod = import_module(mod_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/channels/apps.py", line 6, in <module>
    import daphne.server  # noqa
  File "/var/www/brownpapersession/dev/env-brownpapersession/local/lib/python2.7/site-packages/daphne/server.py", line 171
    async def handle_reply(self, protocol, message):
            ^
SyntaxError: invalid syntax
``` 

I just noticed it's in the README.rst, while `setup.py` still has:
```
...
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Web Environment",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: BSD License",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.4",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Topic :: Internet :: WWW/HTTP",
    ],
...
```

**Comment by andrewgodwin** [comment]
Yes, Daphne 2 does not support Python 2, it requires version 3.5 or up, as well as a Channels 2 project (not Channels 1). Sorry for leaving the classifiers in there - I have removed them now in f18078e.

I recommend you pin your requirements to `daphne~=1.4` if you need to stick with the 1.x series.
