### ISSUE TITLE
Return 404 for invalid routes

### ISSUE THREAD

**Issue by acdha** [django/daphne#165]
Currently, any request which doesn't match a route causes an error-level log event. HTTP requests are mapped to the usual Django 404 path but websockets cause a traceback like this:

```
$ pipenv run daphne -p 8001 inventory.asgi:application
Loading .env environment variables…
[2018-02-07 20:04:12] botocore.credentials INFO Found credentials in shared credentials file: ~/.aws/credentials
[2018-02-07 20:04:12] daphne.cli INFO Starting server at tcp:port=8001:interface=127.0.0.1
[2018-02-07 20:04:12] daphne.server INFO HTTP/2 support not enabled (install the http2 and tls Twisted extras)
[2018-02-07 20:04:12] daphne.server INFO Listening on endpoint tcp:port=8001:interface=127.0.0.1
[2018-02-07 20:04:28] daphne.ws_protocol ERROR Traceback (most recent call last):
  File "/Users/cadams/.virtualenvs/inventory-api-prototype-yJheR8NE/lib/python3.6/site-packages/daphne/ws_protocol.py", line 76, in onConnect
    "subprotocols": subprotocols,
  File "/Users/cadams/.virtualenvs/inventory-api-prototype-yJheR8NE/lib/python3.6/site-packages/daphne/server.py", line 177, in create_application
    application_instance = self.application(scope=scope)
  File "/Users/cadams/.virtualenvs/inventory-api-prototype-yJheR8NE/lib/python3.6/site-packages/channels/routing.py", line 51, in __call__
    return self.application_mapping[scope["type"]](scope)
  File "/Users/cadams/.virtualenvs/inventory-api-prototype-yJheR8NE/lib/python3.6/site-packages/channels/routing.py", line 89, in __call__
    raise ValueError("No route found for path %r." % path)
ValueError: No route found for path 'foo/bar'.
```

```
$ wst client ws://localhost:8001/foo/bar
Client closed connection (Abnormal) 
```

**Comment by andrewgodwin** [comment]
This is tricky, as a 404 response is different between WebSocket and HTTP, but we should do it.

**Comment by hishnash** [comment]
what about adding a `websocket.deny` a message type that can be sent downstream instead of `websocket.accept` including `status` and `headers: [(.., ...)]` HTTP status/headers etc they would then be added to the HTTP response of the handshake request.

or let he `websocket.close` message take these options (but they would naturally be ignored if you send  `websocket.close` after having already accepted the connection.

**Comment by ssahilsahil798** [comment]
I have a working websocket example for you at http://www.freemediaweb.com
If you are using Daphne redis and django_channels This would resolve your problem of 404---
As per your log your nginx or whatever you use is working fine. problem may lie in one or both of the following -
1- routing.py
2-javascript file

ValueError: No route found for path 'foo/bar'. ---this line in you log suggest that REGEX function is creating problem.

**Comment by abhrj** [comment]
@andrewgodwin Even if 404 response is not possible for websockets, could the log entry be made more succinct? In the latest version of daphne and channels, the log I see is:

```
 [none] [28997] [ERROR] ws_protocol.py:108 [Failure instance: Traceback: <class 'ValueError'>: No route found for path '/comments/dfdf'.
 /home/venv/lib/python3.6/site-packages/twisted/internet/defer.py:500:errback
 /home/venv/lib/python3.6/site-packages/twisted/internet/defer.py:567:_startRunCallbacks
 /home/venv/lib/python3.6/site-packages/twisted/internet/defer.py:653:_runCallbacks
 /home/venv/lib/python3.6/site-packages/twisted/internet/defer.py:1442:gotResult
 --- <exception caught here> ---
 /home/venv/lib/python3.6/site-packages/twisted/internet/defer.py:1384:_inlineCallbacks
 /home/venv/lib/python3.6/site-packages/twisted/python/failure.py:393:throwExceptionIntoGenerator
 /home/venv/lib/python3.6/site-packages/daphne/server.py:186:create_application
 /home/venv/lib/python3.6/site-packages/twisted/python/threadpool.py:250:inContext
 /home/venv/lib/python3.6/site-packages/twisted/python/threadpool.py:266:<lambda>
 /home/venv/lib/python3.6/site-packages/twisted/python/context.py:122:callWithContext
 /home/venv/lib/python3.6/site-packages/twisted/python/context.py:85:callWithContext
 /home/venv/lib/python3.6/site-packages/channels/routing.py:56:__call__
 ./backend/routing.py:38:__call__
 /home/venv/lib/python3.6/site-packages/channels/routing.py:140:__call__
 ]
 [none] [28997] [ERROR] base_events.py:1260 Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /home/venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py:287
 handle: <TimerHandle when=128663.001667604 AsyncioSelectorReactor.callLater.<locals>.run() at /home/venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py:287>
 Traceback (most recent call last):
   File "/usr/lib/python3.6/asyncio/events.py", line 127, in _run
     self._callback(*self._args)
   File "/home/venv/lib/python3.6/site-packages/twisted/internet/asyncioreactor.py", line 290, in run
     f(*args, **kwargs)
   File "/home/venv/lib/python3.6/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
     protocol.connectionLost(reason)
   File "/home/venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 128, in connectionLost
     self._connectionLost(reason)
   File "/home/venv/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 2467, in _connectionLost
     WebSocketProtocol._connectionLost(self, reason)
   File "/home/venv/lib/python3.6/site-packages/autobahn/websocket/protocol.py", line 1096, in _connectionLost
     self._onClose(self.wasClean, WebSocketProtocol.CLOSE_STATUS_CODE_ABNORMAL_CLOSE, "connection was closed uncleanly (%s)" % self.wasNotCleanReason)
   File "/home/venv/lib/python3.6/site-packages/autobahn/twisted/websocket.py", line 171, in _onClose
     self.onClose(wasClean, code, reason)
   File "/home/venv/lib/python3.6/site-packages/daphne/ws_protocol.py", line 146, in onClose
     self.application_queue.put_nowait({
 AttributeError: 'WebSocketProtocol' object has no attribute 'application_queue'
```

**Comment by andrewgodwin** [comment]
That's an error in Daphne that just needs fixing (#194), not deliberate.

**Comment by andrewgodwin** [comment]
Also, going to actually leave this closed as I don't see a way to do 404 for websockets and Django handles it for HTTP.

**Comment by lambdaTW** [comment]
@acdha I got this issue from sentry many times, so I write middleware for handling it. I hope it's the right way to handle this problem If any good idea please let me know, thanks.

```python
from datetime import datetime
from logging import getLogger
from django.urls.exceptions import Resolver404


logger = getLogger(__file__)


class HandleRouteNotFoundMiddleware:

    def __init__(self, inner):
        self.inner = inner

    def __call__(self, scope):
        try:
            inner_instance = self.inner(scope)
        except (Resolver404, ValueError) as e:
            if 'No route found for path' not in str(e) and \
               scope["type"] not in ['http', 'websocket']:
                return inner_instance

            logger.warning(
                f'{datetime.now()} - {e} - {scope}'
            )

            if scope["type"] == "http":
                return self.handle_http_route_error
            elif scope["type"] == "websocket":
                return self.handle_ws_route_error

    async def handle_ws_route_error(self, receive, send):
        await send({"type": "websocket.close"})

    async def handle_http_route_error(self, receive, send):
        await send({
            "type": "http.response.start",
                    "status": 404,
                    "headers": {},
        })
        await send({
            "type": "http.response.body",
            "body": "",
            "more_body": "",
        })
```
---
```python
from core.middleware import HandleRouteNotFoundMiddleware


application = ProtocolTypeRouter({
    'websocket': AuthMiddlewareStack(
        HandleRouteNotFoundMiddleware(
            URLRouter(
                routing.websocket_urlpatterns
            )
        )
    ),
    'channel': router,
    'http': HandleRouteNotFoundMiddleware(
        URLRouter(
            urlpatterns
        )
    )
})
```

**Comment by bocyn** [comment]
I've end up with below code:

middleware.py
``` python

class RouteNotFoundMiddleware:
    def __init__(self, app):
        self.app = app

    async def __call__(self, scope, receive, send):
        try:
            return await self.app(scope, receive, send)
        except ValueError as e:
            if (
                "No route found for path" in str(e)
                and scope["type"] == "websocket"
            ):
                await send({"type": "websocket.close"})
                logger.warning(e)
```

asgi.py

``` python

application = ProtocolTypeRouter(
    {
        "http": get_asgi_application(),
        "websocket": AuthMiddlewareStack(
            RouteNotFoundMiddleware(
                URLRouter(ws.routing.websocket_urlpatterns)
            )
        )
    }
)
```
My environment:

Python 3.8.6
django 3.1.7
channels 3.0.3
daphne 3.0.1
