### ISSUE TITLE
Apps aren't loaded yet error

### ISSUE THREAD

**Issue by rubyxyr** [django/daphne#197]
my asgi.py is 
```
import os
import django
from channels.routing import get_default_application

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "my_project.settings")
django.setup()
application = get_default_application()
```
but when I run my nameko events in my project 
```
nameko run microservice.client:ResultClient --config config.yaml
```
and my ```ResultClient``` has another app's celery tasks code
```
from scheduler.tasks import result_get
result_get.delay(payload['service_name'], payload['uuid'], payload['target_type'])
```
then error appear 
```
Traceback (most recent call last):
  File "./microservice/client/result_client.py", line 16, in result_exists
    from scheduler.tasks import result_get
  File "./scheduler/tasks.py", line 7, in <module>
    from django.contrib.auth.models import User
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "/usr/local/lib/python3.6/site-packages/django/contrib/auth/base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "/usr/local/lib/python3.6/site-packages/django/db/models/base.py", line 100, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 244, in get_containing_app_config
    self.check_apps_ready()
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 127, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```
And in my settings:
```
INSTALLED_APPS = [
   ...
   'scheduler',
   'channels',
]

ASGI_APPLICATION = "my_project.routing.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.environ.get('CHANNEL_REDIS_URL', '')],
        },
    },
}

```

I run ```daphne -b 0.0.0.0 -p 8000 my_project.asgi:application``` in supervisord.

**Comment by andrewgodwin** [comment]
This means your result client is not running `django.setup()` before you access models - it's not a Channels thing.
