### ISSUE TITLE
Apparent infinite loop

### ISSUE THREAD

**Issue by agronick** [django/daphne#223]
I am seeing the same log printing every two seconds 

```
Aug 23 12:22:50  python3[15132]: 2018-08-23 12:22:50,326 WARNING  Application timed out while sending response
Aug 23 12:22:52  python3[15132]: 2018-08-23 12:22:52,330 WARNING  Application timed out while sending response
Aug 23 12:22:54  python3[15132]: 2018-08-23 12:22:54,333 WARNING  Application timed out while sending response
Aug 23 12:22:56  python3[15132]: 2018-08-23 12:22:56,336 WARNING  Application timed out while sending response
Aug 23 12:22:58  python3[15132]: 2018-08-23 12:22:58,339 WARNING  Application timed out while sending response
Aug 23 12:23:00  python3[15132]: 2018-08-23 12:23:00,342 WARNING  Application timed out while sending response
Aug 23 12:23:02  python3[15132]: 2018-08-23 12:23:02,345 WARNING  Application timed out while sending response
Aug 23 12:23:04  python3[15132]: 2018-08-23 12:23:04,348 WARNING  Application timed out while sending response
Aug 23 12:23:06  python3[15132]: 2018-08-23 12:23:06,350 WARNING  Application timed out while sending response
```

It appears that some request did time out but is not being removed. My HTTP timeout is very log (1800 seconds). There appears to be some code path where the timed out request never gets removed. This is a low traffic site so I know a new request isn't timing out for every iteration of this loop. This appears to be a rare error as this is the first time I've seen it.

**Comment by agronick** [comment]
This is fixed now in #237

**Comment by valdemarrolfsen** [comment]
I am seeing this issue in `2.5.0`:

```
[api-6c74b494d4-2kwgd] 2020-09-22 12:07:36,247 WARNING  Application timed out while sending response 
[api-6c74b494d4-7t4p8] 2020-09-22 12:07:44,111 WARNING  Application timed out while sending response 
[api-6c74b494d4-4q9bn] 2020-09-22 12:07:35,723 WARNING  Application timed out while sending response 
[api-6c74b494d4-mlvbs] 2020-09-22 12:07:34,871 WARNING  Application timed out while sending response 
[api-6c74b494d4-84xn9] 2020-09-22 12:07:35,090 WARNING  Application timed out while sending response 
[api-6c74b494d4-gwzrz] 2020-09-22 12:07:35,700 WARNING  Application timed out while sending response 
[api-6c74b494d4-8ntc6] 2020-09-22 12:07:34,486 WARNING  Application timed out while sending response 
[api-6c74b494d4-x2whn] 2020-09-22 12:07:34,451 WARNING  Application timed out while sending response 
[api-6c74b494d4-9lpfm] 2020-09-22 12:07:35,461 WARNING  Application timed out while sending response 
[api-6c74b494d4-spc9h] 2020-09-22 12:07:34,337 WARNING  Application timed out while sending response 
[api-6c74b494d4-2kwgd] 2020-09-22 12:07:36,247 WARNING  Application timed out while sending response 
[api-6c74b494d4-x5prr] 2020-09-22 12:07:36,355 WARNING  Application timed out while sending response 
[api-6c74b494d4-szrxb] 2020-09-22 12:07:35,085 WARNING  Application timed out while sending response 
[api-6c74b494d4-mlvbs] 2020-09-22 12:07:34,871 WARNING  Application timed out while sending response 
[api-6c74b494d4-7t4p8] 2020-09-22 12:07:44,111 WARNING  Application timed out while sending response 
[api-6c74b494d4-84xn9] 2020-09-22 12:07:35,090 WARNING  Application timed out while sending response 
[api-6c74b494d4-dhd79] 2020-09-22 12:07:34,848 WARNING  Application timed out while sending response 
[api-6c74b494d4-ph8mc] 2020-09-22 12:07:41,672 WARNING  Application timed out while sending response 
[api-6c74b494d4-gwzrz] 2020-09-22 12:07:35,701 WARNING  Application timed out while sending response 
[api-6c74b494d4-8ntc6] 2020-09-22 12:07:34,486 WARNING  Application timed out while sending response 
[api-6c74b494d4-spc9h] 2020-09-22 12:07:34,337 WARNING  Application timed out while sending response 
[api-6c74b494d4-2kwgd] 2020-09-22 12:07:36,247 WARNING  Application timed out while sending response 
[api-6c74b494d4-7t4p8] 2020-09-22 12:07:44,111 WARNING  Application timed out while sending response 
[api-6c74b494d4-x5prr] 2020-09-22 12:07:36,355 WARNING  Application timed out while sending response 
[api-6c74b494d4-9lpfm] 2020-09-22 12:07:35,461 WARNING  Application timed out while sending response 
[api-6c74b494d4-szrxb] 2020-09-22 12:07:35,085 WARNING  Application timed out while sending response 
[api-6c74b494d4-mlvbs] 2020-09-22 12:07:34,871 WARNING  Application timed out while sending response 
[api-6c74b494d4-vp8dc] 2020-09-22 12:07:41,120 WARNING  Application timed out while sending response 
[api-6c74b494d4-84xn9] 2020-09-22 12:07:35,090 WARNING  Application timed out while sending response 
[api-6c74b494d4-5sr4t] 2020-09-22 12:07:34,225 WARNING  Application timed out while sending response 
[api-6c74b494d4-gqwv5] 2020-09-22 12:07:34,258 WARNING  Application timed out while sending response 
[api-6c74b494d4-4q9bn] 2020-09-22 12:07:35,723 WARNING  Application timed out while sending response 
[api-6c74b494d4-g4p2x] 2020-09-22 12:07:34,391 WARNING  Application timed out while sending response 
[api-6c74b494d4-lr6mm] 2020-09-22 12:07:35,253 WARNING  Application timed out while sending response 
[api-6c74b494d4-5sr4t] 2020-09-22 12:07:34,225 WARNING  Application timed out while sending response 
[api-6c74b494d4-gqwv5] 2020-09-22 12:07:34,258 WARNING  Application timed out while sending response 
[api-6c74b494d4-x2whn] 2020-09-22 12:07:34,451 WARNING  Application timed out while sending response 
[api-6c74b494d4-g4p2x] 2020-09-22 12:07:34,391 WARNING  Application timed out while sending response 
[api-6c74b494d4-dhd79] 2020-09-22 12:07:34,849 WARNING  Application timed out while sending response 
[api-6c74b494d4-ph8mc] 2020-09-22 12:07:41,672 WARNING  Application timed out while sending response 
[api-6c74b494d4-5sr4t] 2020-09-22 12:07:34,226 WARNING  Application timed out while sending response
```

A theory is that it is related to a web socket that is not closed correctly (close code 1006 from Chrome).

Any idea why this is happening?

**Comment by valdemarrolfsen** [comment]
The issue seems to be related to the fact that the following error is not caught:

```
2020-09-24 12:57:34,895 ERROR    Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at /usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py:287 
handle: <TimerHandle when=1428863.432028082 AsyncioSelectorReactor.callLater.<locals>.run() at /usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py:287> 
Traceback (most recent call last): 
File "/usr/local/lib/python3.8/asyncio/events.py", line 81, in _run 
self._context.run(self._callback, *self._args) 
File "/usr/local/lib/python3.8/site-packages/twisted/internet/asyncioreactor.py", line 290, in run 
f(*args, **kwargs) 
File "/usr/local/lib/python3.8/site-packages/daphne/server.py", line 275, in application_checker 
exception = application_instance.exception() 
asyncio.exceptions.CancelledError
```

**Comment by pranaysharma** [comment]
Is this issue solved?
