### ISSUE TITLE
When using daphne with supervisor ,it crashed!

### ISSUE THREAD

**Issue by heroxxCN** [django/daphne#239]
I am writing a small django project with channels,deploying it with daphne & nginx.
When use command like below,it works well:
daphne --bind 127.0.0.1 --port 8003 my_proj.asgi:application

But I got an error when i use supervisor to manage daphne.
The supervisor configuration is like this:
[program:daphne]
directory=/my/path
command=daphne --bind 127.0.0.1 --port 8003 myproj.asgi:application
user=root
autostart=true
autorestart=true
stderr_logfile=/var/log/daphne_err.log
stdout_logfile=/var/log/daphne_out.log

I checked the daphne_err.log, it lookes like this:
Traceback (most recent call last):
  File "/var/www/py3env/bin/daphne", line 11, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/var/www/py3env/lib/python3.6/site-packages/daphne/cli.py", line 161, in entrypoint
    cls().run(sys.argv[1:])
  File "/var/www/py3env/lib/python3.6/site-packages/daphne/cli.py", line 222, in run
    application = import_by_path(args.application)
  File "/var/www/py3env/lib/python3.6/site-packages/daphne/utils.py", line 11, in import_by_path
    module_path, object_path = path.split(":", 1)
ValueError: not enough values to unpack (expected 2, got 1)

OS:ubuntu 16.04
python 3.6.7

channels 2.1.5
daphne 2.2.3
Django 2.1.3
uWSGI 2.0.17.1

Supervisor is installed at:

/usr/lib/python2.7/dist-packages/supervisor-3.2.0-nspkg.pth

What should I do?
Can anyone help me?

**Comment by heroxxCN** [comment]
OS:ubuntu 16.04
python   3.6.7

asgiref        2.3.2
channels       2.1.5
channels-redis 2.3.2
daphne         2.2.3
Django         2.1.3
django-celery  3.2.2
redis          3.0.1
six            1.11.0
Twisted        18.7.0
uWSGI          2.0.17.1

**Comment by heroxxCN** [comment]
Supervisor is installed at:

/usr/lib/python2.7/dist-packages/supervisor-3.2.0-nspkg.pth

**Comment by heroxxCN** [comment]
I've solved the problem.
I have two supervisord.conf files :
/etc/supervisord.conf
/etc/supervisor/supervisord.conf


when i remove the file in /etc/supervisor,it works well.
