### ISSUE TITLE
Can I use it in pypy?

### ISSUE THREAD

**Issue by Chise1** [django/daphne#297]
Can I use it in pypy?

**Comment by carltongibson** [comment]
Have you tried? (It's not officially supported...)

**Comment by zcl0621** [comment]
i try on pypy3,got some issue.
i used thread to async send some message, got error message.
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/local/lib-python/3/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib-python/3/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./evaluation/tasks.py", line 117, in ai_stage_time_task
    send_total_time(last_time, serializer['total_time'], channel_layer, group_name)
  File "./evaluation/tasks.py", line 48, in send_total_time
    "message": {'message': 'totalTime', 'last_time': last_time, 'total_time': total_time, 'status': True}
  File "/usr/local/site-packages/asgiref/sync.py", line 97, in __call__
    loop_future.result()
  File "/usr/local/lib-python/3/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/local/lib-python/3/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/local/lib-python/3/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/site-packages/asgiref/sync.py", line 129, in _run_event_loop
    tasks = asyncio.Task.all_tasks(loop)
  File "/usr/local/lib-python/3/asyncio/tasks.py", line 66, in all_tasks
    return {t for t in cls._all_tasks if t._loop is loop}
  File "/usr/local/lib-python/3/asyncio/tasks.py", line 66, in <setcomp>
    return {t for t in cls._all_tasks if t._loop is loop}
  File "/usr/local/lib-python/3/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: set changed size during iteration
