### ISSUE TITLE
Unity request dropped with 'Bad Request'.

### ISSUE THREAD

**Issue by magnusjjj** [django/daphne#325]
When sending this particular request, daphne responds with 'bad request', does not hand it over to the attached script, and does not log anything even with full verbosity turned on:

[this text file](https://drive.google.com/file/d/1gOLV9VMopgtW27w2YphzFnPtQzx9KtsX/view?usp=sharing)

I double checked it with the sample
`async def app(scope, receive, send):
    assert scope['type'] == 'http'
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ]
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })`

netcat'ing the request supplied gives a bad request. If you do the same thing with uvicorn instead, it works exactly as expected.

**Comment by carltongibson** [comment]
Hi @magnusjjj Thanks for the report. -- any chance you could dig down a bit to offer a bit more to go on?

**Comment by magnusjjj** [comment]
Not sure where to go from here though. There is literally nothing in the logs from what I can see. You send the request, it sends an 'invalid request' back, and never logs or errors out anywhere. I am a bit stumped. I could go on a hunt in the source i you give me a tip on where to start.

If you want to reproduce, download that file, then use netcat to send it to the server.

**Comment by magnusjjj** [comment]
Retracing my steps, it seems like my verbosity settings got gobbled. Managed to set it, and this wound up in the logs:

CRITICAL Unhandled Error
Traceback (most recent call last):
  File "c:\users\tuxie\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 1750, in _run_once
    handle._run()
  File "c:\users\tuxie\appdata\local\programs\python\python37-32\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\internet\asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\internet\base.py", line 721, in fireSystemEvent
    event.fireEvent()
--- <exception caught here> ---
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\internet\base.py", line 428, in fireEvent
    result = callable(*args, **kwargs)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\daphne\server.py", line 306, in kill_all_applications
    application_instance = details["application_instance"]
builtins.KeyError: 'application_instance'

**Comment by magnusjjj** [comment]
It stopped gobbling my verbosity settings, so got this:

CRITICAL Unhandled Error
Traceback (most recent call last):
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\internet\asyncioreactor.py", line 267, in run
    self._asyncioEventloop.run_forever()
  File "c:\users\tuxie\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 523, in run_forever
    self._run_once()
  File "c:\users\tuxie\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 1750, in _run_once
    handle._run()
  File "c:\users\tuxie\appdata\local\programs\python\python37-32\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
--- <exception caught here> ---
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\python\log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\python\log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\python\context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\python\context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\internet\asyncioreactor.py", line 141, in _readOrWrite
    self._disconnectSelectable(selectable, why, read)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\internet\posixbase.py", line 255, in _disconnectSelectable
    selectable.connectionLost(f)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\internet\tcp.py", line 327, in connectionLost
    protocol.connectionLost(reason)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\twisted\web\http.py", line 2433, in connectionLost
    request.connectionLost(reason)
  File "c:\spb_data\.virtualenvs\testcase-xh4tbbos\lib\site-packages\daphne\http_protocol.py", line 203, in connectionLost
    logger.debug("HTTP disconnect for %s", self.client_addr)
builtins.AttributeError: 'WebRequest' object has no attribute 'client_addr'

**Comment by magnusjjj** [comment]
It seems like it might be the twisted library? Seems odd.

**Comment by magnusjjj** [comment]
Hooray, it is!

**Comment by magnusjjj** [comment]
I tried to make the default example for twisted, but adding a post, and it returns the exact same error.
Still 'not the best', but..
