### ISSUE TITLE
Documentation and Error message

### ISSUE THREAD

**Issue by harem234** [django/daphne#394]
Please Add to documentation that daphne look in to DJANGO_SETTINGS_MODULE in Environment for getting django setting,

And show proper Error when not finding the setting file please.

Thanxs a lot.

**Comment by adamchainz** [comment]
Hi

Daphne is independent of Django, and can run apps written in other frameworks. Django already documents well that `DJANGO_SETTINGS_MODULE` is required, and will raise an error if it is not defined.

What was the situation that lead you to open this ticket? Can you share what happened, so we can see if the error is perhaps hiddend somehow?

Thanks,

Adam

**Comment by harem234** [comment]
Well django defined that DJANGO_SETTINGS_MODULE exists,
And also definded a way to pass it to django's manage.py with out setting it.

So it was a little confusing on the situation that there was a seperate settings file with bunch of setings to guess what daphne was missing in fact and from where daphne was trying to read it!

**Comment by adamchainz** [comment]
That sounds frustrating. Can you share any particular stack trace? Otherwise I don't know what we can do in Daphne.

**Comment by harem234** [comment]
after running the command:
`daphne <django project name>.asgi:application --port 8000 --bind 0.0.0.0 -v2`

i get me an error here is the traceback

Traceback (most recent call last):
  File "/.venv/bin/daphne", line 8, in <module>
    sys.exit(CommandLineInterface.entrypoint())
  File "/.venv/lib/python3.9/site-packages/daphne/cli.py", line 170, in entrypoint
    cls().run(sys.argv[1:])
  File "/.venv/lib/python3.9/site-packages/daphne/cli.py", line 232, in run
    application = import_by_path(args.application)
  File "/.venv/lib/python3.9/site-packages/daphne/utils.py", line 12, in import_by_path
    target = importlib.import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/code/./DJ_EmailUser_Social/asgi.py", line 16, in <module>
    application = get_asgi_application()
  File "/.venv/lib/python3.9/site-packages/django/core/asgi.py", line 12, in get_asgi_application
    django.setup(set_prefix=False)
  File "/.venv/lib/python3.9/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/.venv/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'DJ_EmailUser_Social.settings'

----
Now the problem is i do not know from where daphne is reading the path for Django_settings_module!
so i had to guess.

---
after setting the pass
export DJANGO_SETTINGS_MODULE=DJ_EmailUser_Social.settings.deploy

it is working fine
---

the problem is daphne is reading the <django project name>.asgi file,
that file set a deafult for DJANGO_SETTINGS_MODULE with value of DJ_EmailUser_Social.settings

---

Hope to make this clear for others please
can be confusing !

Thanxs

**Comment by adamchainz** [comment]
> the problem is daphne is reading the .asgi file,
> that file set a deafult for DJANGO_SETTINGS_MODULE with value of DJ_EmailUser_Social.settings

As you have determined, you had a mistake in your `asgi.py` module. So the problem lies not in Daphne, or anything to fix there, but with your module.

I guess the module `DJ_EmailUser_Social.settings` existed when you started your project, so Django's `startproject` template wrote it into `asgi.py`. Then you renamed the settings module but missed editing this reference.

I don't think Daphne should change. The traceback provides enough information to debug the issue with the Django code. Applications can crash at startup in infinite ways, so providing a traceback is a tried and tested way of helping you debug things.

Thanks,

Adam
