### ISSUE TITLE
Twisted exception when TLS is used with Daphne on Windows 10

### ISSUE THREAD

**Issue by raceybe** [django/daphne#433]
I get the following trace back after around 30 seconds from the last request. I'm using Daphne on Windows 10. My Channels version is 2.2.0, and Daphne is 2.3.0, with Twisted at 19.2.0.

The exception appears to come from Twisted, but perhaps may be triggered by Channels.

`2019-05-03 12:41:45,252 ERROR    Exception in callback AsyncioSelectorReactor.callLater.<locals>.run() at c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\internet\asyncioreactor.py:287
handle: <TimerHandle when=56886.125 AsyncioSelectorReactor.callLater.<locals>.run() at c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\internet\asyncioreactor.py:287>
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\internet\asyncioreactor.py", line 290, in run
    f(*args, **kwargs)
  File "c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\web\http.py", line 2339, in forceAbortClient
    self.transport.abortConnection()
  File "c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\protocols\tls.py", line 435, in abortConnection
    self._shutdownTLS()
  File "c:\users\user\virtualenvs\channels_test\lib\site-packages\twisted\protocols\tls.py", line 338, in _shutdownTLS
    shutdownSuccess = self._tlsConnection.shutdown()
AttributeError: 'NoneType' object has no attribute 'shutdown'`

I don't believe I have made any special configuration aside from enabling TLS. I also saw this on my Ubuntu server with a different code base.

**Comment by carltongibson** [comment]
This looks like a Twisted TLS issue. Unless there's a concrete suggestion of a change we can make in Daphne I'm not sure it's actionable here.
