### ISSUE TITLE
TypeError: object HttpResponse can't be used in 'await' expression

### ISSUE THREAD

**Issue by QuvonchbekBobojonov** [django/daphne#502]
```
TypeError: object HttpResponse can't be used in 'await' expression
2024-03-15 11:29:33 ERROR Internal Server Error: /
Traceback (most recent call last):
  File "/Users/darklaki/PycharmProjects/naktutka_web/.venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darklaki/PycharmProjects/naktutka_web/.venv/lib/python3.12/site-packages/whitenoise/middleware.py", line 124, in __call__
    return self.get_response(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darklaki/PycharmProjects/naktutka_web/.venv/lib/python3.12/site-packages/asgiref/sync.py", line 277, in __call__
    return call_result.result()
           ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/darklaki/PycharmProjects/naktutka_web/.venv/lib/python3.12/site-packages/asgiref/sync.py", line 353, in main_wrap
    result = await self.awaitable(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: object HttpResponse can't be used in 'await' expression
2024-03-15 11:29:33 DEBUG HTTP 500 response started for ['127.0.0.1', 49896]
2024-03-15 11:29:33 DEBUG HTTP response chunk for ['127.0.0.1', 49896]
2024-03-15 11:29:33 DEBUG HTTP close for ['127.0.0.1', 49896]
2024-03-15 11:29:33 DEBUG HTTP response complete for ['127.0.0.1', 49896]
HTTP GET / 500 [0.04, 127.0.0.1:49896]
2024-03-15 11:29:33 ERROR HTTP GET / 500 [0.04, 127.0.0.1:49896]
```

**Comment by carltongibson** [comment]
Update your white noise middleware.

**Comment by QuvonchbekBobojonov** [comment]
> Update your white noise middleware.

how can i update

**Comment by Archmonger** [comment]
For future onlookers, ASGI support for `WhiteNoise` has resulted in a fork called [`ServeStatic`](https://github.com/Archmonger/ServeStatic/).
