### ISSUE TITLE
Deprecation warning crashes django app upon runserver

### ISSUE THREAD

**Issue by SkamDart** [django/daphne#76]
During a server migration, I ran into the following warning which was causing the Django app to crash. I have posted my stack trace and requirements.txt below. For now, commenting out the
`raise DeprecationWarning` in `daphne/server.py` allows me to run my app but clearly, that is dangerous. 
[This issue](https://github.com/django/channels/issues/465) is similar but matching daphne and channels versions didn't work 

Any ideas for permanent fixes?

Huge thanks in advance! 🌮 
```
ubuntu@host:~/user$ python3.4 manage.py runserver 0.0.0.0:8000 --settings=foo.bar.production
Performing system checks...

System check identified some issues:

System check identified 1 issue (0 silenced).
January 30, 2017 - 08:18:30
Django version 1.10.1, using settings 'foo.bar.production'
Starting Channels development server at http://0.0.0.0:8000/
Channel layer default (asgiref.inmemory.ChannelLayer)
Quit the server with CONTROL-C.
2017-01-30 08:18:30,941 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-30 08:18:30,947 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-30 08:18:30,952 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
2017-01-30 08:18:30,959 - INFO - worker - Listening on channels http.request, websocket.connect, websocket.disconnect, websocket.receive
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f329a9a2378>
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/channels/management/commands/runserver.py", line 83, in inner_run
    ws_protocols=getattr(settings, 'CHANNELS_WS_PROTOCOLS', None),
  File "/usr/local/lib/python3.4/dist-packages/daphne/server.py", line 41, in __init__
    ''' % self.__class__.__name__)
DeprecationWarning:
                The host/port/unix_socket/file_descriptor keyword arguments to Server are deprecated.
```

_requirements.txt_
```
Django==1.10.1
djangorestframework==3.4.6
drf-nested-routers==0.11.1
Pillow==3.3.1
djoser==0.5.1
gunicorn==19.6.0
dj-database-url==0.4.1
whitenoise==3.2.1
psycopg2==2.6.2
django-widget-tweaks==1.4.1
django-cors-middleware==1.3.1
django-extensions==1.7.4
channels==0.17.2
celery==3.1.24
django-channels-presence==0.0.7
django-phonenumber-field==1.1.0
django-suit==0.2.21
twilio==6.0.0rc12
xlrd==1.0.0
django-s3-storage==0.9.11
pydub==0.16.7
```

**Comment by andrewgodwin** [comment]
This is already fixed in the `master` branch of `channels`, it'll be fixed in the next release of that. The next `daphne` release will downgrade that error to a warning too.

**Comment by SkamDart** [comment]
Great, thanks!
