### ISSUE TITLE
Attempt to disconnect unconnected worker?

### ISSUE THREAD

**Issue by dbarbeau** [django/daphne#93]
Hello,

We are facing a bug on a daphne server, it is quite frequent, but we haven't yet found what triggers it. It looks like it's related to connection loss. 

On Python 2.7.10 with packages:
- Channels 1.0.0
- Daphne 1.0.3
- Twisted 17.1.0
- Django 1.10.6

Here is the traceback:

```
Unhandled Error
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python2.7/site-packages/daphne/server.py", line 101, in run
    reactor.run(installSignalHandlers=self.signal_handlers)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
    self.mainLoop()
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/base.py", line 1255, in mainLoop
    self.doIteration(t)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 252, in _disconnectSelectable
    selectable.readConnectionLost(f)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 272, in readConnectionLost
    self.connectionLost(reason)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/internet/tcp.py", line 292, in connectionLost
    protocol.connectionLost(reason)
  File "/app/.heroku/python/lib/python2.7/site-packages/twisted/web/http.py", line 2015, in connectionLost
    request.connectionLost(reason)
  File "/app/.heroku/python/lib/python2.7/site-packages/daphne/http_protocol.py", line 204, in connectionLost
    self.send_disconnect()
  File "/app/.heroku/python/lib/python2.7/site-packages/daphne/http_protocol.py", line 194, in send_disconnect
    "path": self.unquote(self.path),
  File "/app/.heroku/python/lib/python2.7/site-packages/daphne/http_protocol.py", line 179, in unquote
    return unquote(value).decode("utf8")
  File "/app/.heroku/python/lib/python2.7/urllib.py", line 1238, in unquote
    bits = s.split('%')
exceptions.AttributeError: 'NoneType' object has no attribute 'split'
```

We unfortunately don't know why the connection was lost in the first place but it triggers this error. Looking at Twisted's code, the `self.path` attribute gets set before the `WebRequest.process` method is called and only if the full request was received. If the connection is lost before the full request is ready, `self.path` will be `None` in `WebRequest.send_disconnect`.

We would be grateful if you could provide some insight :)

**Comment by andrewgodwin** [comment]
Yes, it's probably exactly as you describe - if a disconnect happens before the connection is fully established, then it has no path. I'll fix it.

**Comment by andrewgodwin** [comment]
OK, pretty sure that commit will fix it - feel free to try running the development version if you want to check. I'll try to get a release out this weekend.

**Comment by dbarbeau** [comment]
Thank you, I will be running tests soon!

**Comment by dbarbeau** [comment]
Just some feedback : the fix seems to behave properly! Thanks for the quick fix & release ;)
